# compose file to deploy to staging
version: '3'

services:
  etap-backoffice:
    container_name: etap-backoffice
    restart: 'unless-stopped'
    image: 832153567490.dkr.ecr.eu-west-1.amazonaws.com/etap-backoffice:${IMAGE_TAG}
    ports:
      - '8000:8000'
    env_file:
      .env
    volumes:
      - /usr/src/app/node_modules
