version: '3'


services:
  etap-backoffice:
#    image: etap-backoffice:latest
    build:
      context: .
    platform: linux/amd64
    restart: unless-stopped
    container_name: etap-backoffice
    environment:
      NODE_ENV: staging
    env_file:
      - .env
    ports:
      - '3000:3000'
    #    links:
    #      - "etap-db:database"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

