version: '3'


services:
  etap-backoffice:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    environment:
      NODE_ENV: development
    env_file:
      - .env
    ports:
      - '3002:3000'
#    links:
#      - "etap-db:database"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

#  etap-db:
#    image: postgres:latest
#    restart: unless-stopped
#    ports:
#      - 5431:5432
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#    environment:
#      POSTGRES_DB: app_db
#      POSTGRES_USER: app_user
#      POSTGRES_PASSWORD: changeme

#volumes:
#  postgres-data:
